model_path: "CarperAI/openai_summarize_tldr_sft"
model_type: "causal"
tokenizer_path: "EleutherAI/gpt-j-6B"
num_layers_unfrozen: 8

train_args:
  output_dir: "/fsx/home-duyphung/all_checkpoints/gptj-rm-summarize-23Feb"
  num_train_epochs: 2
  logging_steps: 100
  save_strategy: "epoch"
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  warmup_steps: 100
  weight_decay: 0.01
  learning_rate: 5.0e-6
  save_total_limit: 1
  # eval_steps: 10
  logging_dir: "./logs"
  fp16: True
  bf16: False

data_path: "CarperAI/openai_summarize_comparisons"
trainer_type: "sparse"
